package com.wisenut.common.wnsearch;

import org.springframework.stereotype.Component;

@Component
public class WNDefine {
	
	public final static int SERVER_TIMEOUT 				= 10 * 1000;
	
	public final static String COLLECTIONS = "cf_data_sigint,cf_data_imint,cf_data_humint,cf_data_osint,cf_data_masint";
	public final static String COLLECTIONS_KO = "OO정보,영상정보,인간정보,공개정보,계측기호";
	
	public final static String SEARCH_FIELD_SIGINT	= "CF_TITLE,CF_CONTENT,CF_SMR_CONTENT,ORG_DOC_NO,R_FOREST_ANAL_RS,SVM_ANAL_RS";
	public final static String SEARCH_FIELD_HUMINT = "CF_TITLE,HUMAN_REPORT_ATTACHFILE_CONTENT_1,HUMAN_REPORT_ATTACHFILE_CONTENT_2,HUMAN_REPORT_ATTACHFILE_CONTENT_3,HUMAN_REPORT_ATTACHFILE_CONTENT_4,HUMAN_REPORT_ATTACHFILE_CONTENT_5,IM_REPORT_LARGE_CLASS_CD_NM,IM_REPORT_MID_CLASS_CD_NM,IM_REPORT_SMALL_CLASS_NM,WISE_CF_DATA_HUMINT_MENU,R_FOREST_ANAL_RS,SVM_ANAL_RS";
	public final static String SEARCH_FIELD_OSINT = "CF_TITLE,HUMAN_REPORT_ATTACHFILE_CONTENT_1,HUMAN_REPORT_ATTACHFILE_CONTENT_2,HUMAN_REPORT_ATTACHFILE_CONTENT_3,HUMAN_REPORT_ATTACHFILE_CONTENT_4,HUMAN_REPORT_ATTACHFILE_CONTENT_5,IM_REPORT_LARGE_CLASS_CD_NM,IM_REPORT_MID_CLASS_CD_NM,IM_REPORT_SMALL_CLASS_NM,WISE_CF_DATA_HUMINT_MENU,R_FOREST_ANAL_RS,SVM_ANAL_RS";
	public final static String SEARCH_FIELD_MASINT = "CF_TITLE,HUMAN_REPORT_ATTACHFILE_CONTENT_1,HUMAN_REPORT_ATTACHFILE_CONTENT_2,HUMAN_REPORT_ATTACHFILE_CONTENT_3,HUMAN_REPORT_ATTACHFILE_CONTENT_4,HUMAN_REPORT_ATTACHFILE_CONTENT_5,IM_REPORT_LARGE_CLASS_CD_NM,IM_REPORT_MID_CLASS_CD_NM,IM_REPORT_SMALL_CLASS_NM,WISE_CF_DATA_HUMINT_MENU,R_FOREST_ANAL_RS,SVM_ANAL_RS";
	public final static String SEARCH_FIELD_IMINT = "CF_TITLE,ATTACHFILE_CONTENT";
	
	public final static String DOCUMENT_FIELD_SIGINT 		= "DOCID,ORG_DOC_NO,CF_DATE,CF_TITLE,CF_CONTENT/400,CF_SMR_CONTENT,R_FOREST_CF_ANAL_YN,R_FOREST_ANAL_RS,R_FOREST_ANAL_BIGO,XGBOOST_ANAL_RS,XGBOOST_ANAL_BIGO,SVM_ANAL_RS,SVM_ANAL_BIGO,R_FOREST_CF_ANAL_DT,R_FOREST_CF_ANAL_GBN,CF_ID,CF_TIME,CF_CATEGORY,CF_REG_DT,CF_UPD_DT,PMESII_ANAL_RS,PMESII_ANAL_BIGO,TA_CONTENT,ALIAS,TITLE_TERMS,CONTENT_TERMS,TERMS";
	public final static String DOCUMENT_FIELD_HUMINT 		= "DOCID,CF_DATE,HUMAN_REPORT_REG_FORCE_CD,HUMAN_REPORT_SEQ,HUMAN_REPORT_INPUT_YMD,CF_TITLE,HUMAN_REPORT_ATTACHFILE_NM_1,HUMAN_REPORT_ATTACHFILE_CONTENT_1/400,HUMAN_REPORT_ATTACHFILE_NM_2,HUMAN_REPORT_ATTACHFILE_CONTENT_2/400,HUMAN_REPORT_ATTACHFILE_NM_3,HUMAN_REPORT_ATTACHFILE_CONTENT_3,HUMAN_REPORT_ATTACHFILE_NM_4,HUMAN_REPORT_ATTACHFILE_CONTENT_4,HUMAN_REPORT_ATTACHFILE_NM_5,HUMAN_REPORT_ATTACHFILE_CONTENT_5,HUMAN_REPORT_INPUT_YMD_1,IM_ATTACH_FILE_NM1,IM_ATTACH_FILE_NM2,IM_ATTACH_FILE_NM3,UPDR_ID,VALID_TERM,REGR_ID,ROK_US_YN,LIMIT_PROPG_APPL_TERM,REGR_POS_CD,MC_SEQ,REPORT_MGNT_NO,IM_REPORT_LARGE_CLASS_CD,IM_REPORT_MID_CLASS_CD,IM_REPORT_SMALL_CLASS_CD,SLVL_CD,ALL_PROPG_AUTH,SYT_REG_DTIME,REG_DTIME,INTF_DIV,IM_REPORT_LARGE_CLASS_CD_NM,IM_REPORT_MID_CLASS_CD_NM,IM_REPORT_SMALL_CLASS_NM,WISE_CF_DATA_HUMINT_MENU,ALIAS,TERMS,TOPIC,XGBOOST_ANAL_RS,R_FOREST_ANAL_RS,SVM_ANAL_RS,PMESII_ANAL_RS,PMESII_ANAL_BIGO";
	public final static String DOCUMENT_FIELD_OSINT  		= "DOCID,CF_DATE,HUMAN_REPORT_REG_FORCE_CD,HUMAN_REPORT_SEQ,HUMAN_REPORT_INPUT_YMD,CF_TITLE,HUMAN_REPORT_ATTACHFILE_NM_1,HUMAN_REPORT_ATTACHFILE_CONTENT_1/400,HUMAN_REPORT_ATTACHFILE_NM_2,HUMAN_REPORT_ATTACHFILE_CONTENT_2/400,HUMAN_REPORT_ATTACHFILE_NM_3,HUMAN_REPORT_ATTACHFILE_CONTENT_3,HUMAN_REPORT_ATTACHFILE_NM_4,HUMAN_REPORT_ATTACHFILE_CONTENT_4,HUMAN_REPORT_ATTACHFILE_NM_5,HUMAN_REPORT_ATTACHFILE_CONTENT_5,HUMAN_REPORT_INPUT_YMD_1,IM_ATTACH_FILE_NM1,IM_ATTACH_FILE_NM2,IM_ATTACH_FILE_NM3,UPDR_ID,VALID_TERM,REGR_ID,ROK_US_YN,LIMIT_PROPG_APPL_TERM,REGR_POS_CD,MC_SEQ,REPORT_MGNT_NO,IM_REPORT_LARGE_CLASS_CD,IM_REPORT_MID_CLASS_CD,IM_REPORT_SMALL_CLASS_CD,SLVL_CD,ALL_PROPG_AUTH,SYT_REG_DTIME,REG_DTIME,INTF_DIV,IM_REPORT_LARGE_CLASS_CD_NM,IM_REPORT_MID_CLASS_CD_NM,IM_REPORT_SMALL_CLASS_NM,WISE_CF_DATA_HUMINT_MENU,ALIAS,TERMS,TOPIC,XGBOOST_ANAL_RS,R_FOREST_ANAL_RS,SVM_ANAL_RS,PMESII_ANAL_RS,PMESII_ANAL_BIGO";
	public final static String DOCUMENT_FIELD_MASINT 		= "DOCID,CF_DATE,HUMAN_REPORT_REG_FORCE_CD,HUMAN_REPORT_SEQ,HUMAN_REPORT_INPUT_YMD,CF_TITLE,HUMAN_REPORT_ATTACHFILE_NM_1,HUMAN_REPORT_ATTACHFILE_CONTENT_1/400,HUMAN_REPORT_ATTACHFILE_NM_2,HUMAN_REPORT_ATTACHFILE_CONTENT_2/400,HUMAN_REPORT_ATTACHFILE_NM_3,HUMAN_REPORT_ATTACHFILE_CONTENT_3,HUMAN_REPORT_ATTACHFILE_NM_4,HUMAN_REPORT_ATTACHFILE_CONTENT_4,HUMAN_REPORT_ATTACHFILE_NM_5,HUMAN_REPORT_ATTACHFILE_CONTENT_5,HUMAN_REPORT_INPUT_YMD_1,IM_ATTACH_FILE_NM1,IM_ATTACH_FILE_NM2,IM_ATTACH_FILE_NM3,UPDR_ID,VALID_TERM,REGR_ID,ROK_US_YN,LIMIT_PROPG_APPL_TERM,REGR_POS_CD,MC_SEQ,REPORT_MGNT_NO,IM_REPORT_LARGE_CLASS_CD,IM_REPORT_MID_CLASS_CD,IM_REPORT_SMALL_CLASS_CD,SLVL_CD,ALL_PROPG_AUTH,SYT_REG_DTIME,REG_DTIME,INTF_DIV,IM_REPORT_LARGE_CLASS_CD_NM,IM_REPORT_MID_CLASS_CD_NM,IM_REPORT_SMALL_CLASS_NM,WISE_CF_DATA_HUMINT_MENU,ALIAS,TERMS,TOPIC,XGBOOST_ANAL_RS,R_FOREST_ANAL_RS,SVM_ANAL_RS,PMESII_ANAL_RS,PMESII_ANAL_BIGO";
	public final static String DOCUMENT_FIELD_IMINT			= "DOCID,CF_DATE,CF_TITLE,ATTACHFILE_CONTENT/400,REPORT_FILE_NM,DECD_REPORT_SEQ,MIS_REG_FORCE_CD,REG_FORCE_CD,JU_MIS_INT_NO,IMG_MIS_NO,IMPO_DCMN_MTTR,REPORT_FILE_SIZE,REG_CENTER_CD,PROPG_YN,IMG_NU,SLVL_CD,REGR_ID,UPDR_ID,REG_DTIME,UPD_DTIME,ALIAS,TERMS,TOPIC,XGBOOST_ANAL_RS,PMESII_ANAL_RS,PMESII_ANAL_BIGO";
	
	public final static String DOWNLOAD_FIELD_SIGINT 		= "CF_DATE,CF_TITLE,CF_CONTENT";
	public final static String DOWNLOAD_FIELD_HUMINT 	= "CF_DATE,CF_TITLE,HUMAN_REPORT_ATTACHFILE_CONTENT_1,HUMAN_REPORT_ATTACHFILE_CONTENT_2";
	public final static String DOWNLOAD_FIELD_OSINT			= "CF_DATE,CF_TITLE,HUMAN_REPORT_ATTACHFILE_CONTENT_1,HUMAN_REPORT_ATTACHFILE_CONTENT_2";
	public final static String DOWNLOAD_FIELD_MASINT		= "CF_DATE,CF_TITLE,HUMAN_REPORT_ATTACHFILE_CONTENT_1,HUMAN_REPORT_ATTACHFILE_CONTENT_2";
	public final static String DOWNLOAD_FIELD_IMINT 		= "CF_DATE,CF_TITLE,ATTACHFILE_CONTENT";
	
	public final static String MERGED_COLLECTION = "cf_data";
	public final static String MERGED_DOCUMENT_FIELD = "DOCID, CF_TITLE, CF_CONTENT";

	public final static int GROUP_BY_DOCUMENT_COUNT = 1;
	public final static String GROUP_BY_SORT_FIELD = "CF_DATE/DESC";
	
	final static String CHARACTOR_SET_UTF8 			= "UTF-8";
	final static String CHARACTOR_SET_EUCKR 		= "EUC-KR";
	
	final static int 	QUERY_LOG_ON				= 1;
	final static int 	QUERY_LOG_OFF				= 0;
	
	final static int	USE_HIGHLIGHT_ON			= 1;
	final static int 	USE_HIGHLIGHT_OFF			= 0;
	
	final static int	USE_SNIPPET_ON				= 1;
	final static int 	USE_SNIPPET_OFF				= 0;
	
	final static int 	PAGE_START					= 0;
	final static int 	RESULT_COUNT				= 10;
	
	final static int 	EXTEND_OR_ON				= 1;
	final static int 	EXTEND_OR_OFF				= 0;
	
	final static int 	AND_OPERATOR_ON				= 1;
	final static int 	AND_OPERATOR_OFF			= 0;
	
	final static int 	USE_LA_ON 					= 1;
	final static int 	USE_LA_OFF 					= 0; 
	
	final static int 	IGNORE_CASE_ON 				= 1;
	final static int 	IGNORE_CASE_OFF				= 0; 
	
	final static int 	USER_ORIGINAL_ON 			= 1; 
	final static int 	USER_ORIGINAL_OFF 			= 0; 
		
	final static int 	USER_SYNONYM_ON 			= 1; 
	final static int 	USER_SYNONYM_OFF 			= 0; 
	
	public static String STATE_DATE					= "1970/01/01";
	public static String END_DATE					= WNUtil.getDate();
}
