/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-07-01 06:59:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jhs_005fsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1624512923190L));
    _jspx_dependants.put("jar:file:/C:/01.edu_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/mvcSuperSearch/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl.release();
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta content=\"IE=Edge\" http-equiv=\"X-UA-Compatible\" />\r\n");
      out.write("<title>통합검색</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/css/style.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/css/default.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/css/jquery-ui.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/ark/css/ark.css\" media=\"screen\" >\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/ark/js/beta.fix.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/ark/js/ark.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/js/datepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/js/search.js\"></script><!--  검색관련 js -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("		");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("        <!-- header -->\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("        \r\n");
      out.write("        	<form name=\"search\" id=\"search\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/superSearch/getSearchList.wn\" method=\"get\">\r\n");
      out.write("			<input type=\"hidden\" name=\"startCount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.condition.startCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("			<input type=\"hidden\" name=\"sort\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.condition.sort}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("			<input type=\"hidden\" name=\"collection\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.condition.collection}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("			<input type=\"hidden\" name=\"range\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.condition.startCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("			<input type=\"hidden\" name=\"startDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.condition.startDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("			<input type=\"hidden\" name=\"endDate\" value= \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.condition.endDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>			\r\n");
      out.write("			<input type=\"hidden\" name=\"searchField\"value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.condition.searchField}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("			<input type=\"hidden\" name=\"reQuery\" />\r\n");
      out.write("			<input type=\"hidden\" name=\"realQuery\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.condition.realQuery}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("        	\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"top clearfix\">\r\n");
      out.write("				<h1><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/images/logo.PNG\" alt=\"대한지방행정공제회\" /></a></h1>\r\n");
      out.write("				<div class=\"sch_wrap\">\r\n");
      out.write("					<select>\r\n");
      out.write("						<option>통합검색</option>\r\n");
      out.write("					</select>\r\n");
      out.write("					\r\n");
      out.write("					<input name=\"query\" id=\"query\" type=\"text\" value=\"\" onKeypress=\"javascript:pressCheck((event),this);\" autocomplete=\"off\"/>\r\n");
      out.write("					\r\n");
      out.write("					<!-- 검색 버튼 부분 -->\r\n");
      out.write("					<input type=\"submit\" class=\"btn_sch\" title=\"검색\"/>\r\n");
      out.write("				</div>\r\n");
      out.write("				<a href=\"#\" class=\"detail_btn\">상세검색</a>\r\n");
      out.write("				<div class=\"sch_opt\">\r\n");
      out.write("					<input type=\"checkbox\" id=\"result_chk\" checked=\"checked\" />\r\n");
      out.write("					<label for=\"result_chk\"><span></span>결과 내 재검색</label>\r\n");
      out.write("				</div>\r\n");
      out.write("                <dl class=\"related_keyword\">\r\n");
      out.write("                    <dt>연관검색어</dt>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                    <dd><a href=\"#\">검색어</a></dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("\r\n");
      out.write("				<!-- 자동완성 -->\r\n");
      out.write("				<div class=\"auto_keyword\" style=\"display:none\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>도교육청</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>도연구대회</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>도교육감</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>어말하기대회</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>학생문화원</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>시교육지원청</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>도서관</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>교육과학연구원</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>교육박물관제</a></li>\r\n");
      out.write("						<li><a href=\"#\"><span>제주</span>영어교육도시</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<p><a href=\"#\">자동완성 기능 끄기</a></p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- //자동완성 -->\r\n");
      out.write("			</div>\r\n");
      out.write("			</form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- //header -->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <!-- container -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- leftArea -->\r\n");
      out.write("            <div class=\"leftArea\">\r\n");
      out.write("                <ul class=\"lnb\">\r\n");
      out.write("                    <li><a class=\"on\" href=\"#\">통합검색<span>(3,482)</span></a></li>\r\n");
      out.write("                    <li><a href=\"#\">전자결재<span>(100)</span></a></li>\r\n");
      out.write("                    <li><a href=\"#\">게시판<span>(100)</span></a></li>\r\n");
      out.write("                    <li><a href=\"#\">지식<span>(100)</span></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"optionArea\">\r\n");
      out.write("                    <dl class=\"align\">\r\n");
      out.write("                        <dt>정렬</dt>\r\n");
      out.write("                        <dd class=\"divi on\"><a href=\"\">정확도</a></dd>\r\n");
      out.write("                        <dd class=\"divi\"><a class=\"arr\" href=\"\">최신순</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                    <dl class=\"area\">\r\n");
      out.write("                        <dt>검색범위</dt>\r\n");
      out.write("                        <dd class=\"divi on\"><a href=\"\">전체</a></dd>\r\n");
      out.write("                        <dd class=\"divi\"><a href=\"\">제목</a></dd>\r\n");
      out.write("                        <dd class=\"divi\"><a href=\"\">내용</a></dd>\r\n");
      out.write("                        <dd class=\"divi\"><a href=\"\">첨부</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                    <dl class=\"date\">\r\n");
      out.write("                        <dt>검색기간</dt>\r\n");
      out.write("                        <dd class=\"divi on\"><a href=\"\">전체</a></dd>\r\n");
      out.write("                        <dd class=\"divi\"><a href=\"\">1주</a></dd>\r\n");
      out.write("                        <dd class=\"divi\"><a href=\"\">1달</a></dd>\r\n");
      out.write("                        <dd class=\"divi\"><a href=\"\">1년</a></dd>\r\n");
      out.write("                        <dd class=\"cal_box\">\r\n");
      out.write("                            <span><input type=\"text\" /><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/images/icon_day.gif\" alt=\"달력\" /></a></span>\r\n");
      out.write("                            <span><input type=\"text\" /><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/images/icon_day.gif\" alt=\"달력\" /></a></span>\r\n");
      out.write("                        </dd>\r\n");
      out.write("                        <dd><a href=\"#\" class=\"align_btn\">검색</a></dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //leftArea -->\r\n");
      out.write("            <!-- rightArea -->\r\n");
      out.write("            <div class=\"rightArea\">\r\n");
      out.write("                <div class=\"rank\">\r\n");
      out.write("                    <p>인기검색어</p>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><span class=\"rank_num0\">1</span><a href=\"\">기획재정부</a><span class=\"rank_stay\"> -</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num0\">2</span><a href=\"\">기획재정부기획재정부</a><span class=\"rank_stay\"> -</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num0\">3</span><a href=\"\">기획재정부</a><span class=\"rank_up\">1</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num\">4</span><a href=\"\">기획재정부</a><span class=\"rank_up\">1</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num\">5</span><a href=\"\">기획재정부</a><span class=\"rank_down\">2</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num\">6</span><a href=\"\">기획재정부</a><span class=\"rank_new\">NEW</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num\">7</span><a href=\"\">기획재정부</a><span class=\"rank_stay\"> -</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num\">8</span><a href=\"\">기획재정부</a><span class=\"rank_up\">1</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num\">9</span><a href=\"\">기획재정부</a><span class=\"rank_up\">1</span></li>\r\n");
      out.write("                        <li><span class=\"rank_num\">10</span><a href=\"\">기획재정부</a><span class=\"rank_new\">NEW</span></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"my_keyword\">\r\n");
      out.write("                    <p>내가 찾은 검색어</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"\">&middot; 전시</a>\r\n");
      out.write("                            <a class=\"btn_close\" href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/images/icon_close.gif\" alt=\"close\"></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"\">&middot; 특별전</a>\r\n");
      out.write("                            <a class=\"btn_close\" href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/images/icon_close.gif\" alt=\"close\"></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"my_keyword\">\r\n");
      out.write("                    <p>최근 본 문서</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"\" class=\"tit\">&middot; 전시전시전시전시전시전시전시전시전시</a>\r\n");
      out.write("                            <a class=\"btn_close\" href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/images/icon_close.gif\" alt=\"close\"></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"\" class=\"tit\">&middot; 특별전</a>\r\n");
      out.write("                            <a class=\"btn_close\" href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/search/images/icon_close.gif\" alt=\"close\"></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //rightArea -->\r\n");
      out.write("            <!-- contents -->\r\n");
      out.write("            <div class=\"contents\">\r\n");
      out.write("                <div class=\"result_top\">\r\n");
      out.write("                    <strong>'검색어'</strong>에 대한 검색결과는 총[3,482]건 입니다.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sectit01\">\r\n");
      out.write("                    <h2>dctn<span>(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.dctn.DocumentSet.collectionCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></h2>\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     	\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sectit01\">\r\n");
      out.write("                    <h2>doc<span>(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colList.doc.DocumentSet.collectionCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></h2>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn_num\">\r\n");
      out.write("                    <a class=\"num\" href=\"#\">&lt;&lt;</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">&lt;</a>\r\n");
      out.write("                    <a class=\"num click \" href=\"#\">1</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">2</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">3</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">4</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">5</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">6</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">7</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">8</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">9</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">10</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">&gt;</a>\r\n");
      out.write("                    <a class=\"num\" href=\"#\">&gt;&gt;</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //contents -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- //container -->\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/search/jhs_search.jsp(179,21) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search/jhs_search.jsp(179,21) '${colList.dctn.Document }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${colList.dctn.Document }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/search/jhs_search.jsp(179,21) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dctn");
      // /WEB-INF/views/search/jhs_search.jsp(179,21) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	                     ");
            if (_jspx_meth_c_005fimport_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/search/jhs_search.jsp(180,22) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("./result/res_dctn.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_eval_c_005fimport_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_c_005fimport_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_c_005fimport_005f0[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fimport_005f0);
          }
          do {
            out.write("\r\n");
            out.write("	                   \r\n");
            out.write("	                     ");
            if (_jspx_meth_c_005fparam_005f0(_jspx_th_c_005fimport_005f0, _jspx_page_context, _jspx_push_body_count_c_005fimport_005f0))
              return true;
            out.write("\r\n");
            out.write("	                     ");
            if (_jspx_meth_c_005fparam_005f1(_jspx_th_c_005fimport_005f0, _jspx_page_context, _jspx_push_body_count_c_005fimport_005f0))
              return true;
            out.write("\r\n");
            out.write("	                     ");
            if (_jspx_meth_c_005fparam_005f2(_jspx_th_c_005fimport_005f0, _jspx_page_context, _jspx_push_body_count_c_005fimport_005f0))
              return true;
            out.write("\r\n");
            out.write("                     ");
            int evalDoAfterBody = _jspx_th_c_005fimport_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_c_005fimport_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_c_005fimport_005f0[0]--;
          }
        }
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fimport_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fimport_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f0_reused = false;
    try {
      _jspx_th_c_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fimport_005f0);
      // /WEB-INF/views/search/jhs_search.jsp(182,22) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setName("HDWD_NM");
      // /WEB-INF/views/search/jhs_search.jsp(182,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctn.HDWD_NM }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f0 = _jspx_th_c_005fparam_005f0.doStartTag();
      if (_jspx_th_c_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
      _jspx_th_c_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fimport_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fimport_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f1 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f1_reused = false;
    try {
      _jspx_th_c_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fimport_005f0);
      // /WEB-INF/views/search/jhs_search.jsp(183,22) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f1.setName("DATE");
      // /WEB-INF/views/search/jhs_search.jsp(183,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctn.DATE }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f1 = _jspx_th_c_005fparam_005f1.doStartTag();
      if (_jspx_th_c_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f1);
      _jspx_th_c_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fimport_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fimport_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f2 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f2_reused = false;
    try {
      _jspx_th_c_005fparam_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fimport_005f0);
      // /WEB-INF/views/search/jhs_search.jsp(184,22) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f2.setName("TMNL_DEF");
      // /WEB-INF/views/search/jhs_search.jsp(184,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f2.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctn.TMNL_DEF }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f2 = _jspx_th_c_005fparam_005f2.doStartTag();
      if (_jspx_th_c_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f2);
      _jspx_th_c_005fparam_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f2_reused);
    }
    return false;
  }
}
