/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-07-01 01:22:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/./common/top.jsp", Long.valueOf(1624496942917L));
    _jspx_dependants.put("/WEB-INF/views/./common/sideBar.jsp", Long.valueOf(1624496942916L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1624512923190L));
    _jspx_dependants.put("jar:file:/C:/01.edu_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/mvcSuperSearch/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/./common/../common/include.jsp", Long.valueOf(1624496942916L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>Classficator Manager</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Wrapper -->\r\n");
      out.write("  <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar - Brand -->\r\n");
      out.write("      <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("        <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("          <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sidebar-brand-text mx-3\">Classficator<sup>1.0</sup></div >\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Divider -->\r\n");
      out.write("      <hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Nav Item - Dashboard -->\r\n");
      out.write("      <li class=\"nav-item ");
      out.print(request.getRequestURI().contains("/dashboard") ? "active" : "" );
      out.write("\" >\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-tachometer-alt\"></i>\r\n");
      out.write("          <span>현황판</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item ");
      out.print(request.getRequestURI().contains("/server/server") ? "active" : "" );
      out.write("\" >\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-wrench\"></i>\r\n");
      out.write("          <span>서버관리</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item ");
      out.print(request.getRequestURI().contains("/act/study") ? "active" : "" );
      out.write("\" >\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-cog\"></i>\r\n");
      out.write("          <span>학습관리</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item ");
      out.print(request.getRequestURI().contains("/run/run") ? "active" : "" );
      out.write("\" >\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-spinner\"></i>\r\n");
      out.write("          <span>실행관리</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item ");
      out.print(request.getRequestURI().contains("/act/act") ? "active" : "" );
      out.write("\" >\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-desktop\"></i>\r\n");
      out.write("          <span>시뮬레이터</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("<!--       Divider\r\n");
      out.write("      <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("      Heading\r\n");
      out.write("      <div class=\"sidebar-heading\" >\r\n");
      out.write("         관리도구\r\n");
      out.write("      </div>\r\n");
      out.write(" -->\r\n");
      out.write("      <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Nav Item - Utilities Collapse Menu -->\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Nav Item - Utilities Collapse Menu -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Divider -->\r\n");
      out.write("     <!--  <hr class=\"sidebar-divider\"> -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Heading -->\r\n");
      out.write("    <!--   <div class=\"sidebar-heading\">\r\n");
      out.write("        Addons\r\n");
      out.write("      </div> -->\r\n");
      out.write("<!-- \r\n");
      out.write("      Nav Item - Pages Collapse Menu\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePages\" aria-expanded=\"true\" aria-controls=\"collapsePages\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-folder\"></i>\r\n");
      out.write("          <span>Pages</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div id=\"collapsePages\" class=\"collapse\" aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("          <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("            <h6 class=\"collapse-header\">Login Screens:</h6>\r\n");
      out.write("            <a class=\"collapse-item\" href=\"login.html\">Login</a>\r\n");
      out.write("            <a class=\"collapse-item\" href=\"register.html\">Register</a>\r\n");
      out.write("            <a class=\"collapse-item\" href=\"forgot-password.html\">Forgot Password</a>\r\n");
      out.write("            <div class=\"collapse-divider\"></div>\r\n");
      out.write("            <h6 class=\"collapse-header\">Other Pages:</h6>\r\n");
      out.write("            <a class=\"collapse-item\" href=\"404.html\">404 Page</a>\r\n");
      out.write("            <a class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      Nav Item - Charts\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"charts.html\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-chart-area\"></i>\r\n");
      out.write("          <span>Charts</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      Nav Item - Tables\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"tables.html\">\r\n");
      out.write("          <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("          <span>Tables</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write(" -->\r\n");
      out.write("      <!-- Divider -->\r\n");
      out.write("      <hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("      <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("        <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("    <!-- End of Sidebar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Content Wrapper -->\r\n");
      out.write("    <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Main Content -->\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Topbar -->\r\n");
      out.write("  <!-- Custom fonts for this template-->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <!-- <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\"> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template-->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2/css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- alertify -->\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath());
      out.write("/resources/alertifyjs/css/alertify.min.css\" rel=\"stylesheet\">	\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core JavaScript-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/jquery-oLoader-v0.1/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/jquery-oLoader-v0.1/js/jquery.oLoader.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Core plugin JavaScript-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom scripts for all pages-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/common.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/datepicker.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <!-- alertify -->\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath());
      out.write("/resources/alertifyjs/alertify.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("          <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("            <i class=\"fa fa-bars\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("          <!-- Topbar Search -->\r\n");
      out.write("          <!-- <form class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("            <div class=\"input-group\">\r\n");
      out.write("              <input type=\"text\" class=\"form-control bg-light border-0 small\" placeholder=\"Search for...\" aria-label=\"Search\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("              <div class=\"input-group-append\">\r\n");
      out.write("                <button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form> -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Topbar Navbar -->\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - User Information -->\r\n");
      out.write("            <li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                <span class=\"mr-2 d-none d-lg-inline text-gray-800 large\">행정안전부 | 안전 생활불편 통합 신고 시스템 관리도구</span>\r\n");
      out.write("                <!-- <img class=\"img-profile rounded-circle\" src=\"https://source.unsplash.com/QAB-WJcbgJk/60x60\"> -->\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("              <div class=\"nav-link dropdown-toggle\">\r\n");
      out.write("                <span class=\"mr-2 d-none d-lg-inline text-gray-800 large\">");
      out.print(session.getAttribute("id"));
      out.write(" 님</span>\r\n");
      out.write("	            <a href=\"javascript:fn_logout();\" class=\"btn btn-primary btn-icon-split btn-sm\">\r\n");
      out.write("	              <span class=\"text\">로그아웃</span>\r\n");
      out.write("	            </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End of Topbar -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("        <!-- Begin Page Content -->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Page Heading -->\r\n");
      out.write("          <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("            <h1 class=\"h3 mb-0 text-gray-800\">현황판</h1>\r\n");
      out.write("           	<div class=\"col-xl-3 text-right\" >\r\n");
      out.write("               <select class=\"form-control\" id=\"slt_server\"  >\r\n");
      out.write("               </select >\r\n");
      out.write("            </div  >\r\n");
      out.write("            <!-- <a href=\"#\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\"><i class=\"fas fa-download fa-sm text-white-50\"></i> Generate Report</a> -->\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Content Row -->\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-4 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-primary shadow h-100 py-2\" >\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\">서버상태</div>\r\n");
      out.write("                      <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                        <div class=\"col-auto\">\r\n");
      out.write("                          <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\" id=\"dv_server_status\">100%</div>\r\n");
      out.write("                        </div >\r\n");
      out.write("                        <div class=\"col\" id=\"dv_server_status_text\">\r\n");
      out.write("                          <!-- <div class=\"progress progress-sm mr-2\">\r\n");
      out.write("                            <div class=\"progress-bar bg-info\" role=\"progressbar\" style=\"width: 100%\" aria-valuenow=\"50\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                          </div> -->\r\n");
      out.write("                          정상 가동\r\n");
      out.write("                        </div>\r\n");
      out.write("                        	\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-4 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-success shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">학습진행상태 </div>\r\n");
      out.write("                      <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                        <div class=\"col-auto\">\r\n");
      out.write("                          <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\" id=\"dv_progress_bar\">100%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                          <div class=\"progress progress-sm mr-2\">\r\n");
      out.write("                            <div class=\"progress-bar bg-info\" role=\"progressbar\" id=\"progress_bar\" style=\"width: 100%\" aria-valuenow=\"50\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Earnings (Monthly) Card Example -->\r\n");
      out.write("            <div class=\"col-xl-4 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-info shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div class=\"text-xs font-weight-bold text-info text-uppercase mb-1\">모델정보</div>\r\n");
      out.write("                      <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                        <div class=\"col-auto\">\r\n");
      out.write("                          <div class=\"h5 mb-0 mr-3 font-weight-bold\">Model : </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col font-weight-bold\" id=\"dv_model_nm\">\r\n");
      out.write("                          확인 중\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Pending Requests Card Example -->\r\n");
      out.write("            <!-- <div class=\"col-xl-3 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card border-left-warning shadow h-100 py-2\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                    <div class=\"col mr-2\">\r\n");
      out.write("                      <div class=\"text-xs font-weight-bold text-warning text-uppercase mb-1\">학습데이터</div>\r\n");
      out.write("                      <div class=\"row no-gutters align-items-center\">\r\n");
      out.write("                        <div class=\"col-auto\">\r\n");
      out.write("                          <div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">100%</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                          <div class=\"progress progress-sm mr-2\">\r\n");
      out.write("                            <div class=\"progress-bar bg-info\" role=\"progressbar\" style=\"width: 100%\" aria-valuenow=\"50\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                      <i class=\"fas fa-clipboard-list fa-2x text-gray-300\" ></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div> -->\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Content Row -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Area Chart -->\r\n");
      out.write("            <div class=\"col-xl-12 col-lg-7\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"card shadow mb-4\">\r\n");
      out.write("                <div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\r\n");
      out.write("                  <h6 class=\"m-0 font-weight-bold text-primary\">학습데이터 등록현황</h6 >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <div class=\"chart-bar\">\r\n");
      out.write("                    <canvas id=\"myBarChart\"></canvas >\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div> \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core JavaScript-->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2//vendor/jquery/jquery.min.js\"></script >\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2//vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2//vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2//vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/bootstrap-sbadmin2//js/demo/chart-pie-demo.js\"></script >\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\" >\r\n");
      out.write("  \r\n");
      out.write("//Set new default font family and font color to mimic Bootstrap's default styling\r\n");
      out.write("	Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif';\r\n");
      out.write("	Chart.defaults.global.defaultFontColor = '#858796';\r\n");
      out.write("	 \r\n");
      out.write("	var timerId = null;\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	 \r\n");
      out.write("		fn_getServerList();\r\n");
      out.write("	 \r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$('#slt_server').change(function(){\r\n");
      out.write("		\r\n");
      out.write("		fn_initDash();\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  	function fn_initDash(){\r\n");
      out.write("\r\n");
      out.write("		fn_get_barchart_data();\r\n");
      out.write("		fn_getServerSatatus();\r\n");
      out.write("		fn_getModelInfo();\r\n");
      out.write("		timerId = setInterval(fn_getStudyStatus, 1000);\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("  \r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	function fn_getModelInfo() {\r\n");
      out.write("  		\r\n");
      out.write("  		$.ajax({\r\n");
      out.write("  			type: \"post\",\r\n");
      out.write("  			url : \"");
      out.print( request.getContextPath());
      out.write("/run/getModelInfo.wn\",\r\n");
      out.write("  			data: {\r\n");
      out.write("  				cfsv_id: $('#slt_server').val()\r\n");
      out.write("  			},\r\n");
      out.write("  			success: function(data) {\r\n");
      out.write("  				\r\n");
      out.write("  				//data.modelNm\r\n");
      out.write("  				\r\n");
      out.write("  				$('#dv_model_nm').text(data.modelNm);\r\n");
      out.write("  				\r\n");
      out.write("  				\r\n");
      out.write("  			},\r\n");
      out.write("			complete : function(data) {\r\n");
      out.write("			}\r\n");
      out.write("  		\r\n");
      out.write("  		})\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("\r\n");
      out.write("	//서버상태조회\r\n");
      out.write("	function fn_getServerSatatus(){\r\n");
      out.write("		\r\n");
      out.write("		$('#dv_server_status').text(\"0%\");\r\n");
      out.write("		$('#dv_server_status_text').text(\"상태 체크 중\");\r\n");
      out.write("    \r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: \"post\",\r\n");
      out.write("			url : \"");
      out.print( request.getContextPath());
      out.write("/run/getServerSatatus.wn\",\r\n");
      out.write("			data: {\r\n");
      out.write("				cfsv_id: $('#slt_server').val()\r\n");
      out.write("			},\r\n");
      out.write("			success: function(data) {\r\n");
      out.write("				var status = data.status;\r\n");
      out.write("				if(status == \"BREAK\"){\r\n");
      out.write("					$('#dv_server_status_text').text(\"서버 정지상태\");\r\n");
      out.write("					$('#dv_server_status').text(\"0%\");\r\n");
      out.write("				}else{\r\n");
      out.write("					$('#dv_server_status').text(\"100%\");\r\n");
      out.write("					$('#dv_server_status_text').text(\"정상\");\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			complete : function(data) {\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("	//학습 상태 체크\r\n");
      out.write("	function fn_getStudyStatus(){\r\n");
      out.write("		\r\n");
      out.write("		$('#progress_bar').attr(\"style\" , \"width:0%;\");\r\n");
      out.write("		$('#progress_bar').text(\"0% Complete\");\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: \"post\",\r\n");
      out.write("			url : \"");
      out.print( request.getContextPath());
      out.write("/run/getStudyStatus.wn\",\r\n");
      out.write("			data: {\r\n");
      out.write("				cfsv_id: $('#slt_server').val()\r\n");
      out.write("			},\r\n");
      out.write("			success: function(data) {\r\n");
      out.write("				if(data.response) {\r\n");
      out.write("					var setPer = data.progress;\r\n");
      out.write("					var status = data.status;\r\n");
      out.write("					\r\n");
      out.write("					if(status == \"READY\"){\r\n");
      out.write("						\r\n");
      out.write("						//if(isNewCheck) alertify.success('이전 학습이 완료 되었습니다.');\r\n");
      out.write("						//else alert('학습이 완료 되었습니다.');\r\n");
      out.write("						\r\n");
      out.write("						$('#progress_bar').attr(\"style\" , \"width:100%;\");\r\n");
      out.write("						$('#progress_bar').text(\"100% Complete\");\r\n");
      out.write("						$('#dv_progress_bar').text(\"100%\");\r\n");
      out.write("						if(timerId != null) {\r\n");
      out.write("					        clearInterval(timerId);\r\n");
      out.write("					    }\r\n");
      out.write("						\r\n");
      out.write("					}else{\r\n");
      out.write("						\r\n");
      out.write("						$('#progress_bar').attr(\"style\" , \"width:\" + setPer + \";\");\r\n");
      out.write("						$('#progress_bar').text(status + \" \" + setPer);\r\n");
      out.write("						$('#dv_progress_bar').text(setPer + \"%\");\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			complete : function(data) {\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  function number_format(number, decimals, dec_point, thousands_sep) {\r\n");
      out.write("    // *     example: number_format(1234.56, 2, ',', ' ');\r\n");
      out.write("    // *     return: '1 234,56'\r\n");
      out.write("    number = (number + '').replace(',', '').replace(' ', '');\r\n");
      out.write("    var n = !isFinite(+number) ? 0 : +number,\r\n");
      out.write("      prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),\r\n");
      out.write("      sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,\r\n");
      out.write("      dec = (typeof dec_point === 'undefined') ? '.' : dec_point,\r\n");
      out.write("      s = '',\r\n");
      out.write("      toFixedFix = function(n, prec) {\r\n");
      out.write("        var k = Math.pow(10, prec);\r\n");
      out.write("        return '' + Math.round(n * k) / k;\r\n");
      out.write("      };\r\n");
      out.write("    // Fix for IE parseFloat(0.55).toFixed(0) = 0;\r\n");
      out.write("    s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');\r\n");
      out.write("    if (s[0].length > 3) {\r\n");
      out.write("      s[0] = s[0].replace(/\\B(?=(?:\\d{3})+(?!\\d))/g, sep);\r\n");
      out.write("    }\r\n");
      out.write("    if ((s[1] || '').length < prec) {\r\n");
      out.write("      s[1] = s[1] || '';\r\n");
      out.write("      s[1] += new Array(prec - s[1].length + 1).join('0');\r\n");
      out.write("    }\r\n");
      out.write("    return s.join(dec);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("	//서버선택 셀렉트박스\r\n");
      out.write("	function fn_getServerList(pageNum) {\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"");
      out.print( request.getContextPath());
      out.write("/code/getServerList.wn\",\r\n");
      out.write("			data : $('#frm_search').serialize(),\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("\r\n");
      out.write("			success : function(data) {\r\n");
      out.write("\r\n");
      out.write("				var list = data.serverList;\r\n");
      out.write("				var option = \"\";\r\n");
      out.write("				var cnt = 0;\r\n");
      out.write("				if(Object.keys(list).length > 0){\r\n");
      out.write("					$.each(list, function(key, value) {\r\n");
      out.write("						cnt++;\r\n");
      out.write("						option += '<option value=\"' + this.cfsv_id + '\">' + this.cfsv_nm + '</option>';\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("					$('#slt_server').html(option);\r\n");
      out.write("					\r\n");
      out.write("				}else{\r\n");
      out.write("					$('#slt_server').html(option);\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("			},\r\n");
      out.write("			complete : function(data) {\r\n");
      out.write("		        fn_initDash();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	function fn_get_barchart_data(){\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"");
      out.print( request.getContextPath());
      out.write("/code/getBarChartData.wn\",\r\n");
      out.write("			data :{\r\n");
      out.write("				\"cfsv_id\" : $('#slt_server').val()\r\n");
      out.write("			},\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("\r\n");
      out.write("			success : function(data) {\r\n");
      out.write("				var kvArray = data.barChartDataList;\r\n");
      out.write("				var cfctNmArray = kvArray.map(function(obj){\r\n");
      out.write("					   return obj.CFCT_NAME;\r\n");
      out.write("					});\r\n");
      out.write("				var cfctCntArray = kvArray.map(function(obj){\r\n");
      out.write("					   return obj.CNT;\r\n");
      out.write("					});\r\n");
      out.write("				fn_draw_chart(cfctNmArray, cfctCntArray);\r\n");
      out.write("			},\r\n");
      out.write("			\r\n");
      out.write("			complete : function(data) {\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("  \r\n");
      out.write("	function fn_draw_chart(labels, datas){\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	// Bar Chart Example\r\n");
      out.write("	  var ctx = document.getElementById(\"myBarChart\");\r\n");
      out.write("	  var myBarChart = new Chart(ctx, {\r\n");
      out.write("	    type: 'bar',\r\n");
      out.write("	    data: {\r\n");
      out.write("	      labels: labels,\r\n");
      out.write("	      datasets: [{\r\n");
      out.write("	        label: \"Revenue\",\r\n");
      out.write("	        backgroundColor: \"#4e73df\",\r\n");
      out.write("	        hoverBackgroundColor: \"#2e59d9\",\r\n");
      out.write("	        borderColor: \"#4e73df\",\r\n");
      out.write("	        data: datas,\r\n");
      out.write("	      }],\r\n");
      out.write("	    },\r\n");
      out.write("	    options: {\r\n");
      out.write("	      maintainAspectRatio: false,\r\n");
      out.write("	      layout: {\r\n");
      out.write("	        padding: {\r\n");
      out.write("	          left: 10,\r\n");
      out.write("	          right: 25,\r\n");
      out.write("	          top: 25,\r\n");
      out.write("	          bottom: 0\r\n");
      out.write("	        }\r\n");
      out.write("	      },\r\n");
      out.write("	      scales: {\r\n");
      out.write("	        xAxes: [{\r\n");
      out.write("	          time: {\r\n");
      out.write("	            unit: 'month'\r\n");
      out.write("	          },\r\n");
      out.write("	          gridLines: {\r\n");
      out.write("	            display: false,\r\n");
      out.write("	            drawBorder: false\r\n");
      out.write("	          },\r\n");
      out.write("	          ticks: {\r\n");
      out.write("	            maxTicksLimit: 20\r\n");
      out.write("	          },\r\n");
      out.write("	          maxBarThickness: 25,\r\n");
      out.write("	        }],\r\n");
      out.write("	        yAxes: [{\r\n");
      out.write("	          ticks: {\r\n");
      out.write("	            min: 0,\r\n");
      out.write("	            max: 10000,\r\n");
      out.write("	            maxTicksLimit: 20,\r\n");
      out.write("	            padding: 10,\r\n");
      out.write("	            // Include a dollar sign in the ticks\r\n");
      out.write("	            callback: function(value, index, values) {\r\n");
      out.write("	              return number_format(value);\r\n");
      out.write("	            }\r\n");
      out.write("	          },\r\n");
      out.write("	          gridLines: {\r\n");
      out.write("	            color: \"rgb(234, 236, 244)\",\r\n");
      out.write("	            zeroLineColor: \"rgb(234, 236, 244)\",\r\n");
      out.write("	            drawBorder: false,\r\n");
      out.write("	            borderDash: [2],\r\n");
      out.write("	            zeroLineBorderDash: [2]\r\n");
      out.write("	          }\r\n");
      out.write("	        }],\r\n");
      out.write("	      },\r\n");
      out.write("	      legend: {\r\n");
      out.write("	        display: false\r\n");
      out.write("	      },\r\n");
      out.write("	      tooltips: {\r\n");
      out.write("	        titleMarginBottom: 10,\r\n");
      out.write("	        titleFontColor: '#6e707e',\r\n");
      out.write("	        titleFontSize: 14,\r\n");
      out.write("	        backgroundColor: \"rgb(255,255,255)\",\r\n");
      out.write("	        bodyFontColor: \"#858796\",\r\n");
      out.write("	        borderColor: '#dddfeb',\r\n");
      out.write("	        borderWidth: 1,\r\n");
      out.write("	        xPadding: 15,\r\n");
      out.write("	        yPadding: 15,\r\n");
      out.write("	        displayColors: false,\r\n");
      out.write("	        caretPadding: 10,\r\n");
      out.write("	        callbacks: {\r\n");
      out.write("	          label: function(tooltipItem, chart) {\r\n");
      out.write("	            var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';\r\n");
      out.write("	            return number_format(tooltipItem.yLabel);\r\n");
      out.write("	          }\r\n");
      out.write("	        }\r\n");
      out.write("	      },\r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("	  \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/./common/sideBar.jsp(9,86) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/main.wn");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/./common/sideBar.jsp(21,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/main.wn");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/./common/sideBar.jsp(27,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/server/serverMove.wn");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/./common/sideBar.jsp(34,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/study/studyMove.wn");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/./common/sideBar.jsp(41,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/run/runMove.wn");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/./common/sideBar.jsp(49,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/act/actMove.wn");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }
}
