/*
 * 분석대상 데이터 테이블 
 */
CREATE TABLE WISE_CF_DATA (
  CF_ID NUMBER(11) constraint prod_id_pk primary key ,
  CF_TIME varchar(50) DEFAULT NULL ,
  CF_CATEGORY varchar(1024) DEFAULT NULL ,
  CF_REG_DT date DEFAULT NULL ,
  CF_UPD_DT date DEFAULT NULL ,
  CF_TITLE varchar(1000) DEFAULT NULL ,
  CF_CONTENT CLOB ,
  CF_ANAL_YN char(1) DEFAULT 'N' ,
  CF_ANAL_RS varchar(100) DEFAULT NULL ,
  CF_ANAL_BIGO varchar(1024) DEFAULT NULL ,
  CF_ANAL_DT date DEFAULT NULL
)
;

/*
 * 자동분류 서버정보 테이블 
 */
CREATE TABLE WISE_CF_SERVER (
  CFSV_ID NUMBER(11) constraint cfsv_id_pk primary key ,
  CFSV_IP char(15) NOT NULL ,
  CFSV_PORT char(5) NOT NULL ,
  CFSV_NM varchar(500) DEFAULT NULL ,
  CFSV_STD_INDIR varchar(500) DEFAULT NULL ,
  CFSV_ANAL_INDIR varchar(500) DEFAULT NULL ,
  CFSV_ANAL_OUTDIR varchar(500) DEFAULT NULL ,
  CFSV_DESC varchar(2000) DEFAULT NULL ,
  CFSV_REG_DT date DEFAULT NULL ,
  CFSV_UPD_DT date DEFAULT NULL
)
;




/*
 * 자동분류 카테고리 테이블 
 */
CREATE TABLE WISE_CF_CATEGORY (
  CFCT_ID NUMBER(11) constraint cfct_id_pk primary key ,
  CFSV_ID NUMBER(11) NOT NULL ,
  CFCT_PR_ID NUMBER(11) DEFAULT NULL ,
  CFCT_VALUE varchar(200) NOT NULL ,
  CFCT_NAME varchar(200) NOT NULL ,
  CFCT_DEPTH NUMBER(11) DEFAULT NULL ,
  CFCT_SORT NUMBER(11) DEFAULT NULL ,
  CFCT_DESC varchar(4000) DEFAULT NULL ,
  CFSV_REG_DT date DEFAULT NULL ,
  CFSV_UPD_DT date DEFAULT NULL
) 
;


/*
 * 자동분류 학습데이터 테이블 
 */
CREATE TABLE WISE_CF_STUDY_DATA (
  CFST_ID NUMBER(11) constraint cfst_id_pk primary key ,
  CFCT_ID NUMBER(11) NOT NULL ,
  CFSV_ID NUMBER(11) NOT NULL ,
  CFST_GUBUN varchar(50)  ,
  CFST_CONTENT CLOB DEFAULT NULL ,
  CFST_REG_DT date DEFAULT NULL ,
  CFST_UPD_DT date DEFAULT NULL
) 

;

