/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-07-01 01:20:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1624512923190L));
    _jspx_dependants.put("jar:file:/C:/01.edu_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/mvcSuperSearch/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<!-- TEST 임시 URL http://localhost:8080/classificatorManager/login/login.wn -->\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap-sbadmin2/vendor/jquery/jquery.js\"></script><!-- jquery load -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/alertifyjs/alertify.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap-sbadmin2/vendor/jquery/jquery.min.js\"></script><!-- Bootstrap core JavaScript-->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap-sbadmin2/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap-sbadmin2/vendor/jquery-easing/jquery.easing.min.js\"></script><!-- Core plugin JavaScript-->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap-sbadmin2/js/sb-admin-2.min.js\"></script><!-- Custom scripts for all pages-->\r\n");
      out.write("  <title>Classficator Manager - Login</title>\r\n");
      out.write("  <!-- Custom fonts, styles for this template-->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap-sbadmin2/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap-sbadmin2/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Outer Row -->\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-xl-10 col-lg-12 col-md-9\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card o-hidden border-0 shadow-lg my-5\">\r\n");
      out.write("          <div class=\"card-body p-0\">\r\n");
      out.write("            <!-- Nested Row within Card Body -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <img class=\"img-fluid px-3 px-sm-4 mt-3 mb-4\" style=\"width: 27rem;\" src=\"");
      out.print( request.getContextPath());
      out.write("/resources/bootstrap-sbadmin2/img/wisenutcla.jpg\" alt=\"Classficator Manage 로그인\">\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"col-lg-6\">\r\n");
      out.write("                <div class=\"p-5\">\r\n");
      out.write("                  <div class=\"text-center\">\r\n");
      out.write("                    <h1 class=\"h4 text-gray-900 mb-4\">Login</h1>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <form id=\"frm\" name=\"frm\" method=\"post\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <input id=\"id\" name=\"id\" type=\"text\" value=\"wisenut\" class=\"form-control form-control-user\" aria-describedby=\"emailHelp\"  onkeypress=\"if( event.keyCode==13 ){fn_loginCheck(1);}\" placeholder=\"Enter your login id...\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <input id=\"pw\" name=\"pw\" type=\"password\" value=\"wisenut1!\" class=\"form-control form-control-user\"  onkeypress=\"if( event.keyCode==13 ){fn_loginCheck(1);}\" placeholder=\"Password\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                   	<a href=\"javascript:fn_loginCheck();\" class=\"btn btn-primary btn-user btn-block\" >\r\n");
      out.write("	                    <span class=\"text\">Login</span>\r\n");
      out.write("                  	</a>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Wrapper -->\r\n");
      out.write("      <!-- End of Main Content -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			sessionStorage.setItem(\"contextpath\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	//입력 초기화\r\n");
      out.write("	function fn_init(){\r\n");
      out.write("		$('#id').val(''); //ID\r\n");
      out.write("		$('#pw').val(''); //비번\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("	//login Check\r\n");
      out.write("	function fn_loginCheck() {\r\n");
      out.write("		\r\n");
      out.write("		if ( $('#id').val().trim().length < 1 ) $('#id').focus();\r\n");
      out.write("		if ( $('#pw').val().trim().length < 1 ) $('#pw').focus();\r\n");
      out.write("		\r\n");
      out.write("		if( ($('#id').val().trim().length === 0) || ($('#pw').val().trim().length === 0) ) {\r\n");
      out.write("			alert(\"로그인 ID 또는 Password를 입력해야 합니다. \\n \"+ $('#id').val().trim()); /* alertify.error(\"로그인 ID를 입력해야 합니다.\"); */\r\n");
      out.write("			$('#pw').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var sRedirectUrl = \"");
      out.print(request.getContextPath());
      out.write("/login/login.wn\";\r\n");
      out.write("\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"");
      out.print(request.getContextPath());
      out.write("/login/authLogin.wn\",\r\n");
      out.write("			data : {	data: $('#frm').serialize(),\r\n");
      out.write("						id: $('#id').val(),\r\n");
      out.write("						pw: $('#pw').val(),\r\n");
      out.write("					}, \r\n");
      out.write("			contentType: 'application/x-www-form-urlencoded; charset=UTF-8',\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("\r\n");
      out.write("			success: function(data) {\r\n");
      out.write("				if(data.ok){\r\n");
      out.write("\r\n");
      out.write("					/* alert(data.id + \"님께서 로그인 하셨습니다. data.id\"); */\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					location.href=\"'");
      out.print(request.getContextPath());
      out.write("'\" + data.redirectUrl + \"\";\r\n");
      out.write("				}else {\r\n");
      out.write("					if(data.loginUserId==null || data.loginUserId.equals(\"\")){                     // id가 Null 이거나 없을 경우\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					alert(\"ID 또는 비밀번호를 다시 한 번 더 확인 하시고 재 시도해 주시기 바랍니다.\"); /* alertify.error(\"문제가 발생하였습니다.\") */\r\n");
      out.write("					location.href=\"");
      out.print(request.getContextPath());
      out.write("\" + data.redirectUrl + \"\";\r\n");
      out.write("				}\r\n");
      out.write("				sRedirectUrl=\"");
      out.print(request.getContextPath());
      out.write("\" + data.redirectUrl + \"\";\r\n");
      out.write("				//fn_init();\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			complete : function(data) {\r\n");
      out.write("				location.href=sRedirectUrl; //react...\r\n");
      out.write("			}\r\n");
      out.write("		})//ajax\r\n");
      out.write("\r\n");
      out.write("	};//fn_loginCheck\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
